"""create bond tranches table.

Revision ID: 6b2870253ccf
Revises: 
Create Date: 2026-08-13 14:21:10.551165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2870253ccf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_tranches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tranche_size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('coupon', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('redemption_terms', sa.Text(), nullable=False),
    sa.Column('ipt_spread_bps', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('final_spread_bps', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fair_value_spread_bps', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('peak_orderbook', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('final_orderbook', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('syndicate', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bond_tranches_isin'), 'bond_tranches', ['isin'], unique=True)
    op.create_index(op.f('ix_bond_tranches_issuer'), 'bond_tranches', ['issuer'], unique=False)
    op.create_index(op.f('ix_bond_tranches_ticker'), 'bond_tranches', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bond_tranches_ticker'), table_name='bond_tranches')
    op.drop_index(op.f('ix_bond_tranches_issuer'), table_name='bond_tranches')
    op.drop_index(op.f('ix_bond_tranches_isin'), table_name='bond_tranches')
    op.drop_table('bond_tranches')
    # ### end Alembic commands ###
