"""create yield curve points table

Revision ID: c1a89d93c619
Revises: 6b2870253ccf
Create Date: 2026-08-19 17:32:15.889016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a89d93c619'
down_revision: Union[str, Sequence[str], None] = '6b2870253ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yield_curve_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('tenor_years', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('yield_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'currency', 'observation_date', 'tenor_years', name='uq_yield_curve_point')
    )
    op.create_index('ix_yield_curve_points_lookup', 'yield_curve_points', ['issuer', 'currency', 'observation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_yield_curve_points_lookup', table_name='yield_curve_points')
    op.drop_table('yield_curve_points')
    # ### end Alembic commands ###
